# NumPy

In [1]:
import numpy as np

In [2]:
myArr = np.array([3,4,5,6])

In [3]:
myArr

array([3, 4, 5, 6])

In [6]:
myArr1 = np.array([23,34,43452525,6] , np.int32)

In [7]:
myArr[0]= 333
myArr

array([333,   4,   5,   6])

# Numpy array creation methods


# There are 5 general mechanism for creating arrays

 # 1. Conversion from other python structures (e.g. lists, tuples) 

In [14]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
listarray.dtype

dtype('int64')

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.size


9

In [18]:
np.array({23,4,3,4})

array({3, 4, 23}, dtype=object)

# 2. Intrinsic numpy array creation objects (eg arange, ones, zeroes etc)

In [19]:
zeroes = np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
zeroes.dtype
zeroes.shape

(2, 3)

In [21]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(1,500,17)
lspace

array([  1.    ,  32.1875,  63.375 ,  94.5625, 125.75  , 156.9375,
       188.125 , 219.3125, 250.5   , 281.6875, 312.875 , 344.0625,
       375.25  , 406.4375, 437.625 , 468.8125, 500.    ])

In [24]:
emp = np.empty((4,6))
emp

array([[4.64415080e-310, 0.00000000e+000, 1.11789341e+253,
        3.17095867e+180, 9.77817447e+199, 1.07332141e+200],
       [2.35900850e+251, 2.38195485e+190, 1.14448945e+243,
        6.01347002e-154, 7.69843824e+218, 9.77817447e+199],
       [1.70887473e+214, 1.70887473e+214, 4.17521448e+199,
        4.25109693e+228, 1.81596891e-152, 1.46923560e+195],
       [7.51303797e+252, 6.01334515e-154, 4.20703996e-186,
        1.02800749e-312, 1.33360892e+241, 4.18529718e-309]])

In [25]:
emp_like = np.empty_like(lspace)
emp_like

array([  1.    ,  32.1875,  63.375 ,  94.5625, 125.75  , 156.9375,
       188.125 , 219.3125, 250.5   , 281.6875, 312.875 , 344.0625,
       375.25  , 406.4375, 437.625 , 468.8125, 500.    ])

In [28]:
np.identity(45)
np.identity(45).shape

(45, 45)

In [35]:
arr = np.arange(99)
arr
arr.shape

(99,)

In [38]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# NumPy Axis

In [40]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
ar.sum(axis=0)

array([12,  8,  9])

In [44]:
ar.sum(axis=1)

array([ 6, 15,  8])

# Numpy attributes and methods

In [46]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [47]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [48]:
ar.ndim

2

In [49]:
ar.size

9

In [50]:
ar.nbytes

72

In [53]:
one = np.array([1,23,4,5,67])

In [54]:
one.argmax()

4

In [55]:
one.argmin()

0

In [56]:
one.argsort()

array([0, 2, 3, 1, 4])

In [57]:
ar.argmax()

6

In [58]:
ar.argmax(axis =0)

array([2, 1, 1])

In [59]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [60]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [61]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

# Numpy Mathematical operations

In [62]:
ar2 = np.array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [63]:
ar+ar2

array([[ 2,  6, 10],
       [ 6, 10,  7],
       [10,  7,  0]])

you cant do this in a python list..

In [64]:
np.sqrt(ar2)

array([[1.        , 2.        , 2.64575131],
       [1.41421356, 2.23606798, 1.        ],
       [1.73205081, 2.44948974, 0.        ]])

In [65]:
 np.where(ar2>5)

(array([0, 2]), array([2, 1]))

In [66]:
np.count_nonzero(ar2)

8

In [67]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [68]:
import sys

In [69]:
py_ar = [0,4,55,2]

In [71]:
np_ar = np.array(py_ar)

In [72]:
sys.getsizeof(1)*len(py_ar)

112

In [73]:
np_ar.itemsize * np_ar.size

32